# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: humanoid/connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19humanoid/connection.proto\x12\x13humanoid.connection\" \n\x0fStateConnection\x12\r\n\x05topic\x18\x01 \x01(\t\"6\n\x11\x43ontrolConnection\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'humanoid.connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATECONNECTION._serialized_start=50
  _STATECONNECTION._serialized_end=82
  _CONTROLCONNECTION._serialized_start=84
  _CONTROLCONNECTION._serialized_end=138
# @@protoc_insertion_point(module_scope)
