# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lemegeton/msg/humanoid/kinematic.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'lemegeton/msg/humanoid/kinematic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lemegeton.msg.common import manipulator_pb2 as lemegeton_dot_msg_dot_common_dot_manipulator__pb2
from lemegeton.msg.common import geometry_pb2 as lemegeton_dot_msg_dot_common_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&lemegeton/msg/humanoid/kinematic.proto\x12\x12humanoid.kinematic\x1a&lemegeton/msg/common/manipulator.proto\x1a#lemegeton/msg/common/geometry.proto\"S\n\x0e\x46orwardRequest\x12\x41\n\x0bjoint_state\x18\x01 \x01(\x0b\x32,.lemegeton.msg.common.manipulator.JointState\"T\n\x0e\x46orwardRespond\x12\x31\n\x04pose\x18\x01 \x01(\x0b\x32#.lemegeton.msg.common.geometry.Pose\x12\x0f\n\x07success\x18\x02 \x01(\x08\"C\n\x0eInverseRequest\x12\x31\n\x04pose\x18\x01 \x01(\x0b\x32#.lemegeton.msg.common.geometry.Pose\"d\n\x0eInverseRespond\x12\x41\n\x0bjoint_state\x18\x01 \x01(\x0b\x32,.lemegeton.msg.common.manipulator.JointState\x12\x0f\n\x07success\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lemegeton.msg.humanoid.kinematic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDREQUEST']._serialized_start=139
  _globals['_FORWARDREQUEST']._serialized_end=222
  _globals['_FORWARDRESPOND']._serialized_start=224
  _globals['_FORWARDRESPOND']._serialized_end=308
  _globals['_INVERSEREQUEST']._serialized_start=310
  _globals['_INVERSEREQUEST']._serialized_end=377
  _globals['_INVERSERESPOND']._serialized_start=379
  _globals['_INVERSERESPOND']._serialized_end=479
# @@protoc_insertion_point(module_scope)
