# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: humanoid/state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from lemegeton.msg.common import manipulator_pb2 as lemegeton_dot_msg_dot_common_dot_manipulator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14humanoid/state.proto\x12\x0ehumanoid.state\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&lemegeton/msg/common/manipulator.proto\"z\n\x0cStateMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05\x66ield\x18\x02 \x03(\t\x12\x0b\n\x03\x64of\x18\x03 \x01(\x05\x12@\n\njointstate\x18\x04 \x01(\x0b\x32,.lemegeton.msg.common.manipulator.JointState\"\xe1\x01\n\x05State\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x04limb\x18\x02 \x01(\x0b\x32\x1c.humanoid.state.StateMessage\x12/\n\tleft_hand\x18\x03 \x01(\x0b\x32\x1c.humanoid.state.StateMessage\x12\x30\n\nright_hand\x18\x04 \x01(\x0b\x32\x1c.humanoid.state.StateMessage\x12\x1a\n\x12\x63\x61n_accept_control\x18\x05 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'humanoid.state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATEMESSAGE._serialized_start=113
  _STATEMESSAGE._serialized_end=235
  _STATE._serialized_start=238
  _STATE._serialized_end=463
# @@protoc_insertion_point(module_scope)
