# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etemplate.proto\x12\x08template\"$\n\x07MESSAGE\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x1b\n\x08RESPONSE\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\x07Service\x12\x30\n\x07REQUEST\x12\x11.template.MESSAGE\x1a\x12.template.RESPONSEb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'template_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=28
  _MESSAGE._serialized_end=64
  _RESPONSE._serialized_start=66
  _RESPONSE._serialized_end=93
  _SERVICE._serialized_start=95
  _SERVICE._serialized_end=154
# @@protoc_insertion_point(module_scope)
