# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solproto/msg/common/geometry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"solproto/msg/common/geometry.proto\x12\x18solproto.common.geometry\"\x1f\n\x07Vector2\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"=\n\x08Polygon2\x12\x31\n\x06points\x18\x01 \x03(\x0b\x32!.solproto.common.geometry.Vector3\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"=\n\x08Polygon3\x12\x31\n\x06points\x18\x01 \x03(\x0b\x32!.solproto.common.geometry.Vector3\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"v\n\x04Pose\x12\x33\n\x08position\x18\x01 \x01(\x0b\x32!.solproto.common.geometry.Vector3\x12\x39\n\x0borientation\x18\x02 \x01(\x0b\x32$.solproto.common.geometry.Quaternion\"{\n\tTransform\x12\x36\n\x0btranslation\x18\x01 \x01(\x0b\x32!.solproto.common.geometry.Vector3\x12\x36\n\x08rotation\x18\x02 \x01(\x0b\x32$.solproto.common.geometry.Quaternion\"n\n\x05Twist\x12\x31\n\x06linear\x18\x01 \x01(\x0b\x32!.solproto.common.geometry.Vector3\x12\x32\n\x07\x61ngular\x18\x02 \x01(\x0b\x32!.solproto.common.geometry.Vector3\"n\n\x05\x41\x63\x63\x65l\x12\x31\n\x06linear\x18\x01 \x01(\x0b\x32!.solproto.common.geometry.Vector3\x12\x32\n\x07\x61ngular\x18\x02 \x01(\x0b\x32!.solproto.common.geometry.Vector3\"m\n\x06Wrench\x12\x30\n\x05\x66orce\x18\x01 \x01(\x0b\x32!.solproto.common.geometry.Vector3\x12\x31\n\x06torque\x18\x02 \x01(\x0b\x32!.solproto.common.geometry.Vector3\"W\n\x07Inertia\x12\x0b\n\x03ixx\x18\x01 \x01(\x01\x12\x0b\n\x03ixy\x18\x02 \x01(\x01\x12\x0b\n\x03ixz\x18\x03 \x01(\x01\x12\x0b\n\x03iyy\x18\x04 \x01(\x01\x12\x0b\n\x03iyz\x18\x05 \x01(\x01\x12\x0b\n\x03izz\x18\x06 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solproto.msg.common.geometry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR2._serialized_start=64
  _VECTOR2._serialized_end=95
  _POLYGON2._serialized_start=97
  _POLYGON2._serialized_end=158
  _VECTOR3._serialized_start=160
  _VECTOR3._serialized_end=202
  _POLYGON3._serialized_start=204
  _POLYGON3._serialized_end=265
  _QUATERNION._serialized_start=267
  _QUATERNION._serialized_end=323
  _POSE._serialized_start=325
  _POSE._serialized_end=443
  _TRANSFORM._serialized_start=445
  _TRANSFORM._serialized_end=568
  _TWIST._serialized_start=570
  _TWIST._serialized_end=680
  _ACCEL._serialized_start=682
  _ACCEL._serialized_end=792
  _WRENCH._serialized_start=794
  _WRENCH._serialized_end=903
  _INERTIA._serialized_start=905
  _INERTIA._serialized_end=992
# @@protoc_insertion_point(module_scope)
