# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solproto/msg/common/manipulator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%solproto/msg/common/manipulator.proto\x12\x1bsolproto.common.manipulator\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n\x0bJointHeader\x12\x0b\n\x03\x64of\x18\x01 \x01(\x05\x12\r\n\x05\x66ield\x18\x02 \x03(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"[\n\nJointState\x12\x11\n\tpositions\x18\x01 \x03(\x01\x12\x12\n\nvelocities\x18\x02 \x03(\x01\x12\x15\n\raccelerations\x18\x03 \x03(\x01\x12\x0f\n\x07\x65\x66\x66orts\x18\x04 \x03(\x01\"\x94\x01\n\x0fTrajectoryPoint\x12\x11\n\tpositions\x18\x01 \x03(\x01\x12\x12\n\nvelocities\x18\x02 \x03(\x01\x12\x15\n\raccelerations\x18\x03 \x03(\x01\x12\x0f\n\x07\x65\x66\x66orts\x18\x04 \x03(\x01\x12\x32\n\x0ftime_from_start\x18\x05 \x01(\x0b\x32\x19.google.protobuf.Duration\"\x89\x01\n\x0fJointTrajectory\x12\x38\n\x06header\x18\x01 \x01(\x0b\x32(.solproto.common.manipulator.JointHeader\x12<\n\x06points\x18\x02 \x03(\x0b\x32,.solproto.common.manipulator.TrajectoryPointb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solproto.msg.common.manipulator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOINTHEADER._serialized_start=135
  _JOINTHEADER._serialized_end=223
  _JOINTSTATE._serialized_start=225
  _JOINTSTATE._serialized_end=316
  _TRAJECTORYPOINT._serialized_start=319
  _TRAJECTORYPOINT._serialized_end=467
  _JOINTTRAJECTORY._serialized_start=470
  _JOINTTRAJECTORY._serialized_end=607
# @@protoc_insertion_point(module_scope)
