services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    network_mode: host  # 改用 host，效能更好，省去 port 轉換
      
  lemegeton-gateway:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: lemegeton-gateway
    container_name: lemegeton-gateway
    restart: always
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ..:/root/workspace/
    ipc: "host"
    privileged: true
    working_dir: /root/workspace
    env_file:
      - path: .env
        required: false
    command: >
      bash -c "
        python3 deploy/main.py"