# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lemegeton/msg/sensor/frame.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from lemegeton.msg.common import blob_pb2 as lemegeton_dot_msg_dot_common_dot_blob__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n lemegeton/msg/sensor/frame.proto\x12\x1alemegeton.msg.sensor.frame\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1flemegeton/msg/common/blob.proto\"\xc1\x01\n\x0b\x43\x61meraFrame\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tcamera_id\x18\x02 \x01(\t\x12\x10\n\x08\x65ncoding\x18\x03 \x01(\t\x12.\n\x05image\x18\x04 \x01(\x0b\x32\x1f.lemegeton.msg.common.blob.Blob\x12.\n\x05\x64\x65pth\x18\x05 \x01(\x0b\x32\x1f.lemegeton.msg.common.blob.Blob\"J\n\tPoseArray\x12\x0e\n\x06joints\x18\x01 \x03(\t\x12-\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1f.lemegeton.msg.common.blob.Blobb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lemegeton.msg.sensor.frame_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAMERAFRAME._serialized_start=131
  _CAMERAFRAME._serialized_end=324
  _POSEARRAY._serialized_start=326
  _POSEARRAY._serialized_end=400
# @@protoc_insertion_point(module_scope)
