# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lemegeton/msg/common/blob.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1flemegeton/msg/common/blob.proto\x12\x19lemegeton.msg.common.blob\"2\n\x04\x42lob\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"U\n\x08\x42lobSpec\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x0e\n\x06offset\x18\x04 \x01(\x04\x12\x0c\n\x04size\x18\x05 \x01(\x04\"d\n\x0c\x42lobEnvelope\x12\x10\n\x08type_url\x18\x01 \x01(\t\x12\x0e\n\x06header\x18\x02 \x01(\x0c\x12\x32\n\x05\x62lobs\x18\x03 \x03(\x0b\x32#.lemegeton.msg.common.blob.BlobSpecb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lemegeton.msg.common.blob_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOB._serialized_start=62
  _BLOB._serialized_end=112
  _BLOBSPEC._serialized_start=114
  _BLOBSPEC._serialized_end=199
  _BLOBENVELOPE._serialized_start=201
  _BLOBENVELOPE._serialized_end=301
# @@protoc_insertion_point(module_scope)
