# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solproto/msg/teleop/remote_control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(solproto/msg/teleop/remote_control.proto\x12\x1esolproto.teleop.remote_control\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n\x13RemoteControlHeader\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x65vice_type\x18\x03 \x01(\t\"\xbb\x03\n\rRemoteControl\x12\x43\n\x06header\x18\x01 \x01(\x0b\x32\x33.solproto.teleop.remote_control.RemoteControlHeader\x12\x10\n\x08linear_x\x18\x02 \x01(\x02\x12\x10\n\x08linear_y\x18\x03 \x01(\x02\x12\x11\n\tangular_z\x18\x04 \x01(\x02\x12\x10\n\x08squat_up\x18\x05 \x01(\x02\x12\x12\n\nsquat_down\x18\x06 \x01(\x02\x12\x12\n\nleft_grasp\x18\x07 \x01(\x02\x12\x13\n\x0bright_grasp\x18\x08 \x01(\x02\x12\x0e\n\x06mode_1\x18\t \x01(\x08\x12\x0e\n\x06mode_2\x18\n \x01(\x08\x12\x0e\n\x06mode_3\x18\x0b \x01(\x08\x12\x0e\n\x06mode_4\x18\x0c \x01(\x08\x12\x11\n\tneck_left\x18\r \x01(\x08\x12\x12\n\nneck_right\x18\x0e \x01(\x08\x12\x0f\n\x07neck_up\x18\x0f \x01(\x08\x12\x11\n\tneck_down\x18\x10 \x01(\x08\x12\x15\n\rtoggle_record\x18\x11 \x01(\x08\x12\x16\n\x0etoggle_control\x18\x12 \x01(\x08\x12\x16\n\x0etoggle_connect\x18\x13 \x01(\x08\x12\r\n\x05\x65stop\x18\x14 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solproto.msg.teleop.remote_control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REMOTECONTROLHEADER._serialized_start=109
  _REMOTECONTROLHEADER._serialized_end=216
  _REMOTECONTROL._serialized_start=219
  _REMOTECONTROL._serialized_end=662
# @@protoc_insertion_point(module_scope)
